INSERT INTO Play_list( artist_name , song_name) VALUES('Drake','Hotline bling');
INSERT INTO Play_list( artist_name , song_name) VALUES('Silento','Watch Me(WHIP/NAE NAE');
INSERT INTO Play_list( artist_name , song_name) VALUES('AKA','Baddest');
INSERT INTO Play_list( artist_name , song_name) VALUES('Florida','I Dont Like It,I Love It');
INSERT INTO Play_list( artist_name , song_name) VALUES('Kwesta','Nomayini');
INSERT INTO Play_list( artist_name , song_name) VALUES('Wiz Khalifa','See You Again');
INSERT INTO Play_list( artist_name , song_name) VALUES('Da Les','P.A.I.D');
INSERT INTO Play_list( artist_name , song_name) VALUES('Da Les','Summer');
INSERT INTO Play_list( artist_name , song_name) VALUES('Dj Switch','Way It Go');
INSERT INTO Play_list( artist_name , song_name) VALUES('Drake','Hold on,We`re  Going Home');
INSERT INTO Play_list( artist_name , song_name) VALUES('The Black Eyed Peas','Where Is Love');
INSERT INTO Play_list( artist_name , song_name) VALUES('K.O','Skhanda Love');
INSERT INTO Play_list( artist_name , song_name) VALUES('Dj Bongz','Ofana Nawe');
INSERT INTO Play_list( artist_name , song_name) VALUES('Jidenna','Classic Man');
INSERT INTO Play_list( artist_name , song_name) VALUES('Empire Cast','What Is love');
INSERT INTO Play_list( artist_name , song_name) VALUES('Prince Kaybee','Better Days');
INSERT INTO Play_list( artist_name , song_name) VALUES('Heavy K','Umoya');
INSERT INTO Play_list( artist_name , song_name) VALUES('Sam Smith','Restart');
INSERT INTO Play_list( artist_name , song_name) VALUES('Justin Bieber','What Do You Mean');
INSERT INTO Play_list( artist_name , song_name) VALUES('Proffessor','Nguye Lona');